xinitrc: start ssh/gpg agents as systemd services

diff --git a/xinitrc b/xinitrc
--- a/xinitrc
+++ b/xinitrc
@@ -3,21 +3,22 @@
 env_file=/tmp/.zenv.agents
 env_ext="${BASH_SOURCE[0]}".env
 
-# For proper PATH and such
-source /etc/profile
+env_pids=()
+exit_cleanup() {
+	systemctl --user --no-block exit &
+	disown # to avoid lockups in case of systemd/dbus fails
+	for pid in "${env_pids[@]}"; do kill "$pid"; done
+}
+trap exit_cleanup TERM INT
 
-# Agents
-create_zenv_file() {
-	touch "$env_file"
+init_zenv_file() {
+	:> "$env_file"
 	chgrp wheel "$env_file"
 	chmod 660 "$env_file"
 }
-if ! pgrep ssh-agent >/dev/null; then
-	create_zenv_file 2>/dev/null
-	ssh-agent | grep -v '^echo' >>"$env_file"
-fi
-pgrep gpg-agent >/dev/null || gpg-agent --daemon
-source "$env_file"
+
+# For proper PATH and such
+source /etc/profile
 
 # Misc env
 export DISPLAY=:1
@@ -26,6 +27,18 @@ export GTK_MODULES="libcanberra-gtk-module.so"
 export XDG_DATA_DIRS="${HOME}/.xdg:/usr/share/enlightenment:/usr/share"
 [[ -r "$env_ext" ]] && source "$env_ext"
 
+# Agents
+init_zenv_file 2>/dev/null
+systemd-run --user --unit=ssh-agent -p Type=forking -- bash -c "ssh-agent | grep -v '^echo ' >>'$env_file'"
+systemd-run --user --unit=gpg-agent -p Type=forking -- gpg-agent --daemon
+source "$env_file"
+
+# Systemd env import and X start
 systemctl --user import-environment
 systemctl --user start startx.target
-exec sleep infinity
+
+sleep infinity &
+env_pids+=( $! )
+wait
+
+exit 0
